### ISSUE TITLE
2022/08/03(Wed.)

### ISSUE THREAD

**Issue by tsuyoshi1222** [tsuyoshi1222/on_boarding#3]
## ToDo

- [x] CS50 - User Interfaces
- [x] CS50 - Testing, CI/CD
- [x] CS50 - Scalability and Security
- [x] 理解度確認MTG1
- [x] 理解度確認MTG2

## 備考

- [ ] 読書 - リーダブルコード
- [ ] 読書 - わかばちゃんと学ぶ Git使い方入門

**Comment by tsuyoshi1222** [comment]
# User Interfaces
@axtx4869 

## ユーザインターフェース
- ユーザインターフェース：Webページの訪問者がそのページと対話する方法

## シングルページアプリケーション
- ひとつのページのみをロードし、JavaScriptを使用してDOM操作が可能になる
- AJAXを利用するとページ全体を毎回ロードする必要がなくなる
```
欠点
- セクションを切り替えてもURLが変わらない

解決方法
- JavaScriptHistoryAPIを使用する
```

## スクロール
javascriptオブジェクト
- `window.innerWidth`：ウィンドウ幅
- `window.innerHeight`：ウィンドウ高さ
- `window.scrollY`：ページ先頭からスクロールしたピクセル数
- `document.body.offsetHeight`：ドキュメント全体の高さ

### 無限スクロール
- 無限スクロール：例）すべての投稿を一度にロードする必要がない場合は、最初の１０件をロードし、ユーザが一番下に達したら次の１０件をロードする。

## アニメーション

## React
- 命令型プログラミング手法
```
例

<h1>0</h1>

let num = parseInt(document.querySelector("h1").innerHTML);
num += 1;
document.querySelector("h1").innerHTML = num;
```
- 宣言型プログラミング（React）
```
例

<h1>{num}</h1>

num += 1;
```
- `React`：コンポーネントとその動作を定義する
- `ReactDOM`：Reactコンポーネントを取得してDOMに挿入する
- `Babel`：`JSX`からブラウザが解釈できるプレーンなjavascriptに翻訳する

### 足し算
作成例

**Comment by tsuyoshi1222** [comment]
# Testing, CI/CD
記述途中
## テスト
作成したコードをテストし、全てが期待通りに動作することを確認することは、ソフトウェア開発プロセスの重要な部分。

## Assert
- `assert`コマンド：`assert function(x) == y`のようにコマンドの後には`True`になるはずの式が続く。式がTrueの場合は何も発生せず、Falseの場合は例外がスローされる。

### Test-Driven Development(テスト駆動開発)
- `テスト駆動開発`：バグを修正するたびにそのバグをチェックするテストを、変更が加えるたびに実行される一連のテストに追加する開発スタイル

## ユニットテスト
- `unittest`：ライブラリ。検出された内容に関する有用な情報を提供する。

1.  最初の行では、テストが記述された順に、成功の場合は一連の`.`、失敗の場合は`F`が表示される。

```
ex.

...F.F
```
2.  失敗した各テストに対して、失敗した関数の名前が与えられる。
```
ex.

FAIL: test_25 (__main__.Tests)
```
3. コメント
```
ex.

Check that 25 is not prime.
```
4. 例外のトレースバック
```
ex.

Traceback (most recent call last):
  File "tests1.py", line 26, in test_25
    self.assertFalse(is_prime(25))
AssertionError: True is not false
```
5. 実行されたテストの数、実行にかかった時間、失敗したテストの数が出力される
```
ex.

Ran 6 tests in 0.001s

FAILED (failures=2)
```
バグが修正されたら以下のようになる
```
ex.

......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
```

## Djangoテスト

**Comment by tsuyoshi1222** [comment]
# Scalability and Security

## スケーラビリティ（拡張性）
サーバがオンプレミスの場合とクラウドの場合の利得
- `カスタマイズ`：独自のサーバをホストすることで、サーバの動作を正確に決定できるようになり、クラウドベースのホスティングよりも柔軟性が高まる
- `専門知識`：クラウド上でアプリケーションをホストする方が、独自のサーバを管理するよりも簡単
- `コスト`：サーバホスティングサイトは利益を上げる必要があるため、オンプレミスのサーバを維持するコストよりも高い料金を請求することになり、クラウドベースのサーバはより高価になる
- `拡張性`：クラウド上でホストする場合は、一般的にスケーリングが容易

## スケーリング
サーバが処理できる要求の数に上限が設定されると、アプリケーションのスケーリングをどのように処理するかを考えることができる。スケーリングには次の二つの方法がある。
- `垂直スケーリング`：垂直スケーリングでは、サーバに負荷がかかったときに、より処理能力の高いサーバを購入または構築する
- `水平スケーリング`：水平スケーリングでは、サーバに負荷がかかった時に、より多くのサーバを購入または構築し、複数のサーバ間で要求を分割する

## ロードバランシング
水平スケーリングを使用すると、どのサーバをどのリクエストに割り当てるかをどのように決定するかという追加の問題に直面する。
- `ランダム`：ロードバランサはリクエストを割り当てるサーバをランダムに決定する
- `ラウンドロビン`：ロードバランサが着信リクエストを受信するサーバを代替する
- `最小接続`：ロードバランサは現在最も少ない要求を処理しているサーバを探し、そのサーバに着信要求を割り当てる。これにより、特定の1つのサーバが過負荷になることを避けれるが、各サーバが現在処理しているリクエストの数をロードバランサが計算するには時間がかかる。

水平方向に拡張する場合には、セッションが別のサーバには保存されていないという問題点がある。セッションの問題を解決するアプローチは以下。
- `スティッキセッション`：ユーザがサイトにアクセスすると、ロードバランサは最初に送信されたサーバを記憶し、必ず同じサーバに送信する、欠点は、多数のユーザが1つのサーバに固執し、そのサーバがクラッシュする恐れがあること
- `データベースセッション`：全てのセッションは、すべてのサーバがアクセスできるデータベースに格納される。欠点は、データベースの読み込みに時間と処理能力がかかること。
- `クライアントサイドセッション`：サーバに情報を保存するのではなく、ユーザのWebブラウザにクッキーとしてローカルに保存する。欠点は、ユーザが別のユーザとしてログインすることを可能にするためのクッキーを作成するというセキュリティ上の懸念と、リクエスト毎にクッキー情報をやりとりするという計算上の懸念がある。

## 自動スケーリング
- `自動スケーリング`：時期によってアクセス数が変わる場合のように、要求の数に応じてサイトで使用されるサーバの数が増減するクラウドコンピューティング

### サーバ障害
- `単一障害点`：障害が発生した後にサイト全体がクラッシュするハードウェア
- `ハートビート要求`：水平方向に拡張する場合、ロードバランサは、各サーバに定期的にハートビート要求を送信することによって、どのサーバがクラッシュしたかを検出し、クラッシュしたサーバへの新しい要求の割り当てを停止できる

## データベースのスケーリング
- `垂直パーティショニング`：この方法では、1つのテーブルに冗長な情報を持たせるのではなく、データを複数の異なるテーブルに分割する
- `水平パーティショニング`：この方法では、同じフォーマットで情報が異なる複数の表を格納する

### データベースの複製
- `単一プライマリ・レプリケーション`：この方法では、複数のデータベースが存在するが、そのうちの1つのみがプライマリ・データベースとみなされる。プライマリ・データベースが更新されると、他のデータベースもプライマリ・データベースと一致するように更新される。欠点はデータベースへの書き込み時に単一障害点がまだ含まれていること。
- `マルチプライマリ・レプリケーション`：この方法では、すべてのデータベースの読み取りと書き込みが可能。これにより、単一障害点の問題は解決されるが、各データベースが他のすべてのデータベースに対する変更を認識する必要があるため、すべてのデータベースを最新の状態に保つことは困難。また、以下の衝突の可能性がある。
```
- `更新の競合`：複数のデータベースがある場合、あるユーザがあるデータベースの行を編集しようとした時、別のユーザが別のデータベースの同じ行を編集しようとすると、データベースの同時期に問題が発生する
- `一意性の競合`：SQLデータベースの各行は一意の識別子
- `削除の競合`
```
